#ifndef GRAMMAR_H
#define GRAMMAR_H

#include "config.h"

#include "string_pool.h"

#include "../vendor/rdesc/include/grammar.h"


#define TK_COUNT 53

#define NT_COUNT 61
#define NT_MAX_ALTERNATIVE_COUNT 10
#define NT_MAX_ALTERNATIVE_SIZE 11

enum tk_id {
	/* Single-char tokens. */
	TK_LBRACE, TK_RBRACE,
	TK_LPAREN, TK_RPAREN,
	TK_LSQ_BRACKET, TK_RSQ_BRACKET,
	TK_COLON, TK_COMMA, TK_DOT, TK_PERCENT, TK_PLUS, TK_SEMI, TK_SLASH,
	TK_STAR,

	/* One or two char tokens. */
	TK_EXCL, TK_EXCL_EQ,
	TK_EQ, TK_EQ_EQ,
	TK_GT, TK_GT_EQ,
	TK_LT, TK_LT_EQ,
	TK_MINUS, TK_RARROW,
	TK_PIPE, TK_PIPE_PIPE,

	/* Two char tokens. */
	TK_AND_AND,

	/* Literals. */
	TK_IDENT, TK_STR, TK_NUMBER, TK_INTEGER,

	/* Keywords. */
	TK_BREAK, TK_CONTINUE, TK_ELSE, TK_ENUM, TK_FALSE, TK_FN, TK_FOR,
	TK_IF, TK_IMPL, TK_LET, TK_LOOP, TK_RETURN, TK_SELF, TK_SELF_TY,
	TK_STRUCT, TK_TRAIT, TK_TRUE, TK_TYPE, TK_WHERE, TK_WHILE,

	TK_EOF, TK_INVALID
};

enum nt_id {
	NT_ITEM,
	NT_ITEM_STRUCT,
	NT_ITEM_ENUM,
	NT_ITEM_TRAIT,
	NT_ITEM_IMPL,
	NT_ITEM_FN,
	NT_ITEM_LET,

	NT_TYPE,
	NT_GENERIC_PARAMS,
	NT_OPTGENERIC_PARAMS,
	NT_BOUNDS,
	NT_BOUNDS_REST,
	NT_OPTBOUNDS,

	NT_ASSOCIATED_ITEMS,
	NT_ASSOCIATED_ITEM,
	NT_OPTASSOCIATED_ITEM_BLOCK,

	NT_STMT,
	NT_STMT_EXPR,
	NT_STMT_RETURN,
	NT_BLOCK,
	NT_BLOCK_STMTS,
	NT_BLOCK_STMTS_EXPR_OPTREST,

	NT_EXPR,
	NT_EXPR_WITH_BLOCK,
	NT_EXPR_WITHOUT_BLOCK,
	NT_OPTEXPR,

	NT_EXPR_IF, NT_EXPR_IF_OPTELSE,
	NT_EXPR_WHILE,

	NT_EXPR_ASGN, NT_EXPR_ASGN_OPTEQ,
	NT_EXPR_LOGIC_OR, NT_EXPR_LOGIC_OR_REST,
	NT_EXPR_LOGIC_AND, NT_EXPR_LOGIC_AND_REST,
	NT_EXPR_EQUALITY, NT_EXPR_EQUALITY_REST, NT_EXPR_EQUALITY_OP,
	NT_EXPR_COMPARISON, NT_EXPR_COMPARISON_REST, NT_EXPR_COMPARISON_OP,
	NT_EXPR_TERM, NT_EXPR_TERM_REST, NT_EXPR_TERM_OP,
	NT_EXPR_FACTOR, NT_EXPR_FACTOR_REST, NT_EXPR_FACTOR_OP,
	NT_EXPR_UNARY_PREFIX, NT_EXPR_UNARY_PREFIX_OP,
	NT_EXPR_UNARY_POSTFIX, NT_EXPR_UNARY_POSTFIX_OPS,
	NT_EXPR_PRIMARY,

	NT_TUPLE,
	NT_TUPLE_ITEMS,
	NT_TUPLE_ITEMS_REST,
	NT_TUPLE_OPTITEMS,

	NT_ITEM_FN_DEF,
	NT_ITEM_FN_PARAMS, NT_ITEM_FN_PARAMS_REST,
	NT_ITEM_FN_OPTPARAMS,

	NT_ITEM_LET_DEF,
};

union seminfo_data {
	struct str_ref str_ref  /* TK_STR or TK_IDENT */;
	Lw_number_t number  /* TK_NUMBER */;
	Lw_integer_t integer  /* TK_INTEGER */;
};

struct seminfo {
	union seminfo_data seminfo;

	int line;
	int col;
};

extern const char *const tk_names[TK_COUNT];

extern const char *const nt_names[NT_COUNT];

extern const struct rdesc_grammar_symbol production_rules
	[NT_COUNT][NT_MAX_ALTERNATIVE_COUNT + 1][NT_MAX_ALTERNATIVE_SIZE + 1];


void token_destroyer(uint16_t id, void *seminfo);


#endif
